-- 台東1館房務學習項目（保養+公區，含印尼文翻譯，共70項）
insert into learning_units (path_id, topic, category, item_name, item_name_id, sort_order)
select (select id from learning_paths where branch_id=(select id from branches where code='TT1') and category='housekeeping'), t.topic, t.category, t.item_name, t.item_name_id, t.sort_order
from (values
  ('保養', '第一週', '窗戶玻璃', 'Kaca jendela', 1),
  ('保養', '第一週', '紗窗清理', 'Pembersihan kasa jendela', 2),
  ('保養', '第一週', '窗溝清理', 'Pembersihan rel jendela', 3),
  ('保養', '第一週', '窗台、平台擦拭', 'Mengelap ambang jendela & permukaan', 4),
  ('保養', '第一週', '輕旅床板擦拭保養殺菌', 'Membersihkan, merawat & mensterilkan papan tempat tidur', 5),
  ('保養', '第一週', '洗屁屁水管除黴', 'Menghilangkan jamur pada selang bidet', 6),
  ('保養', '第一週', '蓮蓬頭清洗', 'Membersihkan shower', 7),
  ('保養', '第二週', '風扇清洗', 'Membersihkan kipas', 8),
  ('保養', '第二週', '沙發套清洗', 'Mencuci sarung sofa', 9),
  ('保養', '第二週', '床檯燈除塵', 'Membersihkan debu lampu meja samping tempat tidur', 10),
  ('保養', '第二週', '房間拖鞋刷洗', 'Menyikat sandal kamar', 11),
  ('保養', '第二週', '地板四角除塵', 'Membersihkan debu di sudut lantai', 12),
  ('保養', '第二週', '輕旅床板擦拭保養殺菌', 'Membersihkan, merawat & mensterilkan papan tempat tidur', 13),
  ('保養', '第三週', '廁所隙縫除黴/地板刷洗', 'Menghilangkan jamur di celah kamar mandi / menyikat lantai', 14),
  ('保養', '第三週', '廁所垃圾桶/洗衣籃清洗', 'Membersihkan tempat sampah & keranjang laundry kamar mandi', 15),
  ('保養', '第三週', '廁所排水孔防臭蓋清洗', 'Membersihkan penutup saluran pembuangan kamar mandi', 16),
  ('保養', '第三週', '廁所小椅子清洗', 'Membersihkan bangku kecil kamar mandi', 17),
  ('保養', '第三週', '浴室置物架清洗', 'Membersihkan rak kamar mandi', 18),
  ('保養', '第三週', '馬桶後方玻璃除水垢', 'Menghilangkan kerak air pada kaca di belakang toilet', 19),
  ('保養', '第三週', '輕旅床板擦拭保養殺菌', 'Membersihkan, merawat & mensterilkan papan tempat tidur', 20),
  ('保養', '第四週', '白鐵除水垢', 'Menghilangkan kerak air pada stainless steel', 21),
  ('保養', '第四週', '馬桶矽膠穩固/細部清理', 'Memperkuat silikon toilet / membersihkan detail', 22),
  ('保養', '第四週', '房間冰箱保養', 'Perawatan kulkas kamar', 23),
  ('保養', '第四週', '大房抱枕套送洗', 'Mengirim sarung bantal besar untuk dicuci', 24),
  ('保養', '第四週', '輕旅床板擦拭保養殺菌', 'Membersihkan, merawat & mensterilkan papan tempat tidur', 25),
  ('保養', '第四週', '大房防水條除水垢', 'Menghilangkan kerak air pada strip tahan air kamar besar', 26),
  ('保養', '第四週', '衛生紙盒鐵架除垢', 'Menghilangkan kerak pada rak besi tisu', 27),
  ('保養', '月任務', '檢查-天花板', 'Pemeriksaan - plafon', 28),
  ('保養', '月任務', '檢查-牆壁', 'Pemeriksaan - dinding', 29),
  ('保養', '月任務', '檢查-層板', 'Pemeriksaan - rak di bawah plafon', 30),
  ('保養', '月任務', '上油漆 (4092百合白)', 'Mengecat (4092 putih lily)', 31),
  ('保養', '月任務', '窗簾保養', 'Perawatan tirai', 32),
  ('保養', '月任務', '曬活性碳', 'Arang aktif', 33),
  ('保養', '月任務', '曬被(奇數月)', 'Menjemur selimut (bulan ganjil)', 34),
  ('保養', '月任務', '曬枕(奇數月)', 'Menjemur bantal (bulan ganjil)', 35),
  ('保養', '季清(1、4、7、10月)', '翻床', 'Membalik kasur', 36),
  ('保養', '季清(1、4、7、10月)', '床底棉絮', 'Membersihkan debu dan serat di bawah tempat tidur', 37),
  ('保養', '季清(2、5、8、11月)', '水盤', 'Membersihkan baki penampung air (drain pan)', 38),
  ('保養', '季清(2、5、8、11月)', '出風口葉片清洗', 'Membersihkan kisi-kisi saluran udara', 39),
  ('保養', '季清(3、6、9、12月)', '主機濾網清洗', 'Membersihkan filter unit utama', 40),
  ('保養', '季清(3、6、9、12月)', '廁所濾網清洗', 'Membersihkan filter ventilasi toilet', 41),
  ('公區', '上午公區', '木地板桌子擦拭', 'Mengelap meja lantai kayu', 42),
  ('公區', '上午公區', '木地板擦拭', 'Mengelap lantai kayu', 43),
  ('公區', '上午公區', '懶骨頭整理', 'Merapikan bean bag', 44),
  ('公區', '上午公區', '瑜珈用品整理', 'Merapikan perlengkapan yoga', 45),
  ('公區', '上午公區', '鋼琴擦拭', 'Mengelap piano', 46),
  ('公區', '上午公區', '洗衣區、後方中島整理', 'Merapikan area laundry & pulau belakang', 47),
  ('公區', '上午公區', '1F書架/展示架擦拭', 'Mengelap rak buku/pajangan lantai 1', 48),
  ('公區', '上午公區', '2F圖書區整理', 'Merapikan area buku lantai 2', 49),
  ('公區', '上午公區', '會議室整理', 'Merapikan ruang rapat', 50),
  ('公區', '上午公區', '微波爐、烤箱、電鍋擦拭', 'Mengelap microwave, oven, rice cooker', 51),
  ('公區', '上午公區', '廚房水槽/滴水盤刷洗', 'Menyikat wastafel & nampan air dapur', 52),
  ('公區', '上午公區', '收垃圾(公廁/中庭/廚房)+掃1F走廊', 'Mengumpulkan sampah + menyapu koridor lantai 1', 53),
  ('公區', '上午公區', '植物澆水(1F公區、大門口、天台)', 'Menyiram tanaman (area umum lantai 1, pintu masuk, rooftop)', 54),
  ('公區', '備品室＆下午公區', '備品分類歸位', 'Mengelompokkan & mengembalikan perlengkapan', 55),
  ('公區', '備品室＆下午公區', '確認報廢、回洗', 'Memastikan barang rusak & yang perlu dicuci ulang', 56),
  ('公區', '備品室＆下午公區', '公廁、淋浴間', 'Toilet umum & ruang shower', 57),
  ('公區', '備品室＆下午公區', '洗衣區、後方中島', 'Area laundry & pulau belakang', 58),
  ('公區', '備品室＆下午公區', '懶骨頭', 'Bean bag', 59),
  ('公區', '備品室＆下午公區', '收垃圾', 'Mengumpulkan sampah', 60),
  ('公區', '備品室＆下午公區', '1/RF玻璃、廚房鏡', 'Kaca lantai 1/rooftop & cermin dapur', 61),
  ('公區', '備品室＆下午公區', '調味料整理、補充', 'Merapikan & mengisi ulang bumbu', 62),
  ('公區', '備品室＆下午公區', '點線香', 'Menyalakan dupa', 63),
  ('公區', '備品室＆下午公區', '電梯', 'Lift', 64),
  ('公區', '備品室＆下午公區', '走廊掃地', 'Menyapu koridor', 65),
  ('公區', '備品室＆下午公區', '全部植物澆水', 'Menyiram semua tanaman', 66),
  ('公區', '備品室＆下午公區', '樓梯/圍牆扶手擦拭', 'Mengelap tangga & pegangan dinding', 67),
  ('公區', '備品室＆下午公區', '飲水機/書架擦拭', 'Mengelap dispenser air & rak buku', 68),
  ('公區', '備品室＆下午公區', '2樓-休憩區整理', 'Merapikan area istirahat lantai 2', 69),
  ('公區', '備品室＆下午公區', 'R樓-會議室整理', 'Merapikan ruang rapat lantai rooftop', 70)) as t(topic, category, item_name, item_name_id, sort_order);

-- 台東1館客務學習項目（學習大綱，共40項）
insert into learning_units (path_id, topic, category, item_name, sort_order)
select (select id from learning_paths where branch_id=(select id from branches where code='TT1') and category='frontdesk'), t.topic, t.category, t.item_name, t.sort_order
from (values
  ('基本概念', '房型', '房間特色', 1),
  ('基本概念', '房型', '特殊規定', 2),
  ('基本概念', '房型', '排房留意', 3),
  ('基本概念', '價格', '各種價格', 4),
  ('基本概念', '價格', '官網價格', 5),
  ('基本概念', '接單', '打單（平台／手工單／來源）', 6),
  ('基本概念', '接單', 'OTA（來源／接單方式）', 7),
  ('基本概念', '接單', 'PMS旅安（自學影片／實作）', 8),
  ('基本概念', '取消政策', '免費取消（一般狀況）', 9),
  ('基本概念', '取消政策', '特殊狀況＆櫃台權限（同意退款／同意延期）', 10),
  ('基本概念', '取消政策', '取消收費', 11),
  ('基本概念', '特殊訂單', '團客', 12),
  ('基本概念', '特殊訂單', '鐵人', 13),
  ('基本概念', '特殊訂單', '合約廠商（路得好友）', 14),
  ('基本概念', '特殊訂單', '折價券／禮券', 15),
  ('基本概念', '特殊訂單', '家長同意書', 16),
  ('業務內容', 'A班', '退房（發票、停車／遺留物遺失卡／檢查煙味／叫車）', 17),
  ('業務內容', 'A班', '開關燈＆音響', 18),
  ('業務內容', 'A班', '掃單＆排房＆早餐券', 19),
  ('業務內容', 'A班', '預授權', 20),
  ('業務內容', 'A班', '續住掃', 21),
  ('業務內容', 'C班', '巡房＆房務日誌', 22),
  ('業務內容', 'C班', '確認入住時間', 23),
  ('業務內容', 'C班', '機動支援（加被加枕／公區維護＆備品位置／拆床／確認房間問題）', 24),
  ('業務內容', 'B班', '辦理入住', 25),
  ('業務內容', 'B班', '入帳', 26),
  ('業務內容', 'B班', '發票', 27),
  ('業務內容', 'B班', '對帳＆結帳', 28),
  ('業務內容', '其他', '公車／計程車／船票', 29),
  ('業務內容', '其他', '點收貨', 30),
  ('業務內容', '其他', '八大稽核', 31),
  ('業務內容', '其他', '停車月租', 32),
  ('業務內容', '其他', '消防警報處理', 33),
  ('業務內容', '其他', '早餐券點收', 34),
  ('業務內容', '其他', '故障排除（水量偏小、花灑卡住、水龍頭阻塞等）', 35),
  ('儲物空間', '儲物空間', '資料室', 36),
  ('儲物空間', '儲物空間', '工具室', 37),
  ('儲物空間', '儲物空間', '地下室', 38),
  ('儲物空間', '儲物空間', '儲藏室', 39),
  ('儲物空間', '儲物空間', '備品室', 40)) as t(topic, category, item_name, sort_order);
