-- 台東1館房號級保養任務範本
insert into room_maintenance_templates (branch_id, cycle, quarter_group, task_name, sort_order)
select (select id from branches where code = 'TT1'), t.cycle, t.quarter_group, t.task_name, t.sort_order
from (values
  ('week1', NULL, '窗戶玻璃', 1),
  ('week1', NULL, '紗窗清理', 2),
  ('week1', NULL, '窗溝清理', 3),
  ('week1', NULL, '窗台、平台擦拭', 4),
  ('week1', NULL, '輕旅床板擦拭保養殺菌', 5),
  ('week1', NULL, '洗屁屁水管除黴', 6),
  ('week1', NULL, '蓮蓬頭清洗', 7),
  ('week2', NULL, '風扇清洗', 1),
  ('week2', NULL, '沙發套清洗', 2),
  ('week2', NULL, '床檯燈除塵', 3),
  ('week2', NULL, '房間拖鞋刷洗', 4),
  ('week2', NULL, '地板四角除塵', 5),
  ('week2', NULL, '輕旅床板擦拭保養殺菌', 6),
  ('week2', NULL, '主機濾網清洗', 7),
  ('week3', NULL, '廁所隙縫除黴/地板刷洗', 1),
  ('week3', NULL, '廁所垃圾桶/洗衣籃清洗', 2),
  ('week3', NULL, '廁所排水孔防臭蓋清洗', 3),
  ('week3', NULL, '廁所小椅子清洗', 4),
  ('week3', NULL, '浴室置物架清洗', 5),
  ('week3', NULL, '馬桶後方玻璃除水垢', 6),
  ('week3', NULL, '輕旅床板擦拭保養殺菌', 7),
  ('week4', NULL, '白鐵除水垢', 1),
  ('week4', NULL, '馬桶矽膠穩固/細部清理', 2),
  ('week4', NULL, '房間冰箱保養', 3),
  ('week4', NULL, '大房抱枕套送洗', 4),
  ('week4', NULL, '輕旅床板擦拭保養殺菌', 5),
  ('week4', NULL, '大房防水條除水垢', 6),
  ('week4', NULL, '衛生紙盒鐵架除垢', 7),
  ('monthly', NULL, '檢查-天花板', 1),
  ('monthly', NULL, '檢查-牆壁', 2),
  ('monthly', NULL, '檢查-層板', 3),
  ('monthly', NULL, '上油漆(4092百合白)', 4),
  ('monthly', NULL, '窗簾保養', 5),
  ('monthly', NULL, '曬被', 6),
  ('monthly', NULL, '曬枕', 7),
  ('quarterly', 1, '翻床', 1),
  ('quarterly', 1, '床底棉絮', 2),
  ('quarterly', 2, '水盤', 1),
  ('quarterly', 2, '出風口葉片清洗', 2),
  ('quarterly', 3, '主機濾網清洗', 1),
  ('quarterly', 3, '廁所濾網清洗', 2)) as t(cycle, quarter_group, task_name, sort_order);
