-- 台東2館客務班別任務（A/B/C班，70項，含每週固定日的清潔項目）
insert into shift_task_templates (branch_id, shift_code, schedule_pattern, schedule_type, schedule_value, task_name, sort_order)
select (select id from branches where code = 'TT2'), t.shift_code, 'ABC', t.schedule_type, t.schedule_value, t.task_name, t.sort_order
from (values
  ('A', 'daily', NULL, '必做項目：共享廚房【補餅乾茶包、椅子擺整齊、桌面清潔】、木地板區【矮桌、懶骨頭擺整齊】館內外地板巡視【掃地】、一定要倒垃圾【1F】；注意口布是否需要先清洗', 1),
  ('A', 'daily', NULL, '解除保全系統，備用房卡本，保留房、房卡歸位', 2),
  ('A', 'daily', NULL, '開燈【行李房、櫃檯招牌燈】、解除公務機轉接、放寵物立牌', 3),
  ('A', 'daily', NULL, '07:00　開冷氣【B1-1樓-25度-微風】、開電磁爐、開電扇【櫃台旁】、開窗、放茶水（含洗杯子）', 4),
  ('A', 'daily', NULL, '平板&平板筆：新增入住須知&開刷卡機，確認電量', 5),
  ('A', 'daily', NULL, '確認退房卡箱及No Show訂單、收門口掛牌（對外的）', 6),
  ('A', 'daily', NULL, '處理昨天交接事項', 7),
  ('A', 'daily', NULL, '掃單、排房', 8),
  ('A', 'daily', NULL, '回覆各平台訊息（FB、IG(檢查陌生訊息)、官方LINE、公機LINE訊息）', 9),
  ('A', 'daily', NULL, '確認MAIL、打單；截圖當日官網價格', 10),
  ('A', 'daily', NULL, '08:00　開冷氣(2-10樓-25度-微風)，僅開啟有住人之樓層以節能', 11),
  ('A', 'daily', NULL, '櫃檯需確認現場已有3間員工專用房【207.208.201】，早上八點到五點之間一定要有三間（六日不用）', 12),
  ('A', 'daily', NULL, '08:30　檢查完房務日誌', 13),
  ('A', 'daily', NULL, '收AGODA費用', 14),
  ('A', 'daily', NULL, '09:00　開音樂', 15),
  ('A', 'daily', NULL, '10:00　開投影機', 16),
  ('A', 'daily', NULL, '11:00　確認客人退畢並檢查房卡數量、2天以上未入住客房改待檢查', 17),
  ('A', 'daily', NULL, '12:00　查帳、訂金更新、關閉投影機', 18),
  ('A', 'daily', NULL, '存前一日營收', 19),
  ('A', 'daily', NULL, '巡視停車場有無關門、有無垃圾、環境清潔、咖啡廳桌面地面清潔', 20),
  ('A', 'daily', NULL, '13:30　檢查發票是否都開立完成，沒開的需交班備註', 21),
  ('A', 'daily', NULL, '清機、結帳、交班', 22),
  ('A', 'daily', NULL, '交接未完成事項給B班，打完14:00前的訂單', 23),
  ('A', 'daily', NULL, '協助巡房', 24),
  ('A', 'daily', NULL, '下班前用酒精擦拭B1共享廚房桌面、旁邊三張小桌子、冰箱門面及把手、用科技海綿刷洗兩個洗手槽、補餅乾，地面清潔', 25),
  ('A', 'weekday', 1, '清潔中島上方玻璃層板、擦拭放置水壺格柵', 26),
  ('A', 'weekday', 2, '清洗排油煙網(兩台電磁爐上方)、清洗水壺', 27),
  ('A', 'weekday', 3, '整理客用冰箱並清潔冰箱，換水製冰儲用水箱，巡視有無超過退房日期之食品飲料需丟棄', 28),
  ('A', 'weekday', 4, '確認調味料庫存是否需要叫貨、除濕劑需不需要乾燥還原(1大3小)、洗杯子', 29),
  ('A', 'weekday', 5, '清潔小烤箱(內網需拿起來刷洗)、洗鍋具', 30),
  ('A', 'weekday', 6, '做下週六預授權（以及當天尚未預授權訂單）、洗碗盤餐具', 31),
  ('A', 'weekday', 0, '清潔櫥櫃門面', 32),
  ('B', 'daily', NULL, '14:00　巡房', 1),
  ('B', 'daily', NULL, '處理早班交接事項、掃單', 2),
  ('B', 'daily', NULL, '回覆各平台訊息（FB、IG、官方LINE、公機LINE訊息）', 3),
  ('B', 'daily', NULL, '確認MAIL、打單', 4),
  ('B', 'daily', NULL, '15:00　查帳、訂金更新', 5),
  ('B', 'daily', NULL, '16:00　開投影機', 6),
  ('B', 'daily', NULL, '17:00　確認客人入住時間', 7),
  ('B', 'daily', NULL, '18:00　關閉投影機', 8),
  ('B', 'daily', NULL, '19:10左右　倒回收（玻璃罐、週一、四）、洗口布、咖啡廳桌面地面清潔', 9),
  ('B', 'daily', NULL, '21:00　旅安關房、製作隔日房務日誌、關音樂、收誠實箱零錢入帳', 10),
  ('B', 'daily', NULL, '上傳今日房務日誌', 11),
  ('B', 'daily', NULL, '檢查發票是否都開，沒開的備註', 12),
  ('B', 'daily', NULL, '清機、結帳、交班', 13),
  ('B', 'daily', NULL, '交接未完成事項給明天A班', 14),
  ('B', 'daily', NULL, '檢查行李房，將非寄放隔夜之行李或物品拖出至櫃檯前方', 15),
  ('B', 'daily', NULL, '22:00　確認咖啡廳有無公休並貼公休掛牌', 16),
  ('B', 'daily', NULL, '上傳晚到表格及櫃檯接待平面圖給保全，上傳當日館內公機人員電話', 17),
  ('B', 'daily', NULL, '確認已入住之房卡有無正確', 18),
  ('B', 'daily', NULL, '打完22:00前的訂單', 19),
  ('B', 'daily', NULL, '上傳客務日誌', 20),
  ('B', 'daily', NULL, '小費箱收到主櫃抽屜、關延長線電源及電磁爐、關電扇（櫃台旁）', 21),
  ('B', 'daily', NULL, '將零用金、筆電、平板收到行李房櫃子、關音響電源', 22),
  ('B', 'daily', NULL, '關燈（櫃台招牌燈、行李房）、關櫃台旁柵欄、櫃檯後窗門', 23),
  ('B', 'daily', NULL, '放退房卡箱、暫離牌、收寵物立牌、掛門口掛牌（對外的、緊急聯絡板）、收茶水', 24),
  ('B', 'daily', NULL, '簽廁所清潔紀錄表（若無C班請B班有巡房的人要簽）', 25),
  ('B', 'daily', NULL, '備用房卡本及保留房並放到保全箱，下班離開櫃台後開啟保全系統', 26),
  ('B', 'daily', NULL, '開啟公務機轉接電話（給保全）', 27),
  ('B', 'weekday', 3, '確認遺留物有無需要丟棄，並在訂單上備註、遺留物表格也需紀錄', 28),
  ('C', 'daily', NULL, '代A班間休', 1),
  ('C', 'daily', NULL, '代B班間休', 2),
  ('C', 'daily', NULL, '催退', 3),
  ('C', 'daily', NULL, '11:00　巡視停車場有無關門、有無垃圾、環境清潔，咖啡廳桌面地面清潔', 4),
  ('C', 'daily', NULL, '14:00　支援房務部', 5),
  ('C', 'daily', NULL, '回覆各平台訊息(IG訊息)', 6),
  ('C', 'daily', NULL, '確認MAIL、打單', 7),
  ('C', 'daily', NULL, '查帳、訂金更新', 8),
  ('C', 'daily', NULL, '簽廁所清潔紀錄表', 9),
  ('C', 'daily', NULL, '巡房', 10)) as t(shift_code, schedule_type, schedule_value, task_name, sort_order);

-- 台東2館店經理巡館清單（原始資料是「主管」欄位任務，含每週二五叫貨提醒）
insert into manager_task_templates (branch_id, task_name, sort_order)
select (select id from branches where code = 'TT2'), t.task_name, t.sort_order
from (values
  ('八月盤點、製卡、迎賓飲料製作（依當月調整）', 1),
  ('各平台評價回覆', 2),
  ('處理待辦事項', 3),
  ('填寫昨日雲端各表單', 4),
  ('確認昨日工作日誌×2', 5),
  ('報修', 6),
  ('確認零用金單據並統計', 7),
  ('叫貨＆採購用品（每週二、五）', 8)
) as t(task_name, sort_order);

-- 台東2館公區保養（早上/下午日常，結構比台東1館簡單很多，沒有分責任區跟月清季清）
insert into public_area_maintenance_templates (branch_id, cycle, task_name, sort_order)
select (select id from branches where code = 'TT2'), t.cycle, t.task_name, t.sort_order
from (values
  ('daily_am', '植物澆水', 1),
  ('daily_am', '公廁、B1公區垃圾', 2),
  ('daily_am', '1F、B1木地板清潔', 3),
  ('daily_am', 'B1洗衣區、廚房', 4),
  ('daily_am', '騎樓、後花園掃地', 5),
  ('daily_am', '桌椅擦拭、補衛生紙', 6),
  ('daily_am', '樓梯扶手、窗台', 7),
  ('daily_pm', '電梯、騎樓掃地、植物澆水', 1),
  ('daily_pm', '公廁、備品室廁所', 2),
  ('daily_pm', '公共區域垃圾', 3),
  ('daily_pm', 'B1洗衣區、廚房', 4),
  ('daily_pm', '樓層地板、飲水機櫃', 5),
  ('daily_pm', '樓梯間地板', 6)
) as t(cycle, task_name, sort_order);
