-- 自評表題目（43題：共同11、主管11、房務10、客務11）
insert into self_eval_templates (category, question_zh, question_id, sort_order)
values
  ('common', '我本月有善盡團隊合作責任，未因個人偏好任意要求調班或變更休假；如遇臨時狀況，也有事先與同部門同事協調補班及工作交接。', NULL, 1),
  ('common', '我本月安排排班、排休及特別休假時，有遵守主管訂定之排班原則，並與同事妥善協調，未因固執個人需求而增加其他同事之工作負擔。', NULL, 2),
  ('common', '不論部門或目前正在執行的工作為何，遇到客人或同事時，我都有保持親切態度、主動問好並提供必要協助。', NULL, 3),
  ('common', '我本月有準時出勤、依規定完成打卡，未發生無故遲到、早退、擅離工作區域或未完成交接之情形。', NULL, 4),
  ('common', '我本月在工作時間內有維持應有之工作紀律，未因私人聊天、使用手機或處理私人事務而影響工作品質。', NULL, 5),
  ('common', '我本月收到主管提醒或改善要求後，有積極調整工作方式，未重複發生相同問題而拒絕改善。', NULL, 6),
  ('common', '我本月有妥善使用及保管公司設備、物品及工作工具，未因疏忽造成遺失、損壞或管理風險。', NULL, 7),
  ('common', '我本月發現設備異常、安全疑慮、客人反映或工作缺失時，有主動回報主管並完成必要紀錄，未隱瞞或延誤處理。', NULL, 8),
  ('common', '我本月與同事溝通時，有保持尊重及理性，未以情緒化、責怪、排擠、散播負面言論或消極不配合等方式影響團隊合作。', NULL, 9),
  ('common', '我本月有尊重客人隱私及公司資訊，未向無關人員談論客人資料、訂房資訊、內部營運或人事內容。', NULL, 10),
  ('common', '我本月有主動了解並遵守公司公告、工作流程及標準作業規範；如有不清楚之處，也有即時向主管確認，而非自行臆測或沿用錯誤做法。', NULL, 11),
  ('management', '我本月在房務或客務部門需要支援時，能作為支援戰力即時補位並協助現場運作。', NULL, 1),
  ('management', '我本月有仔細了解各部門工作事項，確保同事與自身對於工作細節、標準及流程之認知一致。', NULL, 2),
  ('management', '我本月針對公司發布事項，有及時了解、確認並完成佈達，並確認同事已理解及落實。', NULL, 3),
  ('management', '我本月進行人員評核時，有依據實際紀錄及具體事實公平評分，未因私人關係、個人情緒或單一事件影響整體判斷。', NULL, 4),
  ('management', '我本月未擅自向應徵者或在職人員承諾未經公司核可之薪資、福利、採購或其他條件。', NULL, 5),
  ('management', '我本月每日皆有主動巡查現場服務、房況、環境及人員工作狀態；發現問題時能即時提醒、要求改善並持續追蹤。', NULL, 6),
  ('management', '我本月排班及排休時，有依營運需求、人員能力與公平原則安排，並預先確認重要日期之人力是否足夠。', NULL, 7),
  ('management', '我本月處理客訴、突發事件或跨部門問題時，有先完整掌握事實、協調處理、留下紀錄並回報結果，未將問題擱置或選擇蓋牌不回報。', NULL, 8),
  ('management', '我本月有妥善管理出勤、交接、採購、庫存、請款、設備維修及其他主管負責之行政資料，確保內容正確且可追溯。', NULL, 9),
  ('management', '我本月有以身作則遵守公司制度與服務標準，未要求同事遵守但自己例外，或因個人情緒影響管理判斷。', NULL, 10),
  ('management', '我本月有定期檢視人力、工作流程及服務品質，針對重複發生的問題提出具體改善方法並追蹤執行結果。', NULL, 11),
  ('housekeeping', '我本月每次進房前，都有落實三次敲門並以英文詢問三次，確認無人回應後才進入，避免誤入仍有客人在內之房間。', 'Setiap kali akan memasuki kamar pada bulan ini, saya selalu mengetuk pintu tiga kali dan mengucapkan pemberitahuan dalam bahasa Inggris sebanyak tiga kali. Saya baru masuk setelah memastikan tidak ada jawaban untuk menghindari masuk ke kamar yang masih ditempati tamu.', 1),
  ('housekeeping', '我本月發現的所有遺留物都有立即回報工作群組，並確實送至櫃檯依規定處理，未有私自丟棄、取用、私藏或未回報之情形。', 'Semua barang tamu yang tertinggal dan ditemukan pada bulan ini segera saya laporkan melalui grup kerja serta saya serahkan ke meja resepsionis untuk diproses sesuai ketentuan. Saya tidak membuang, menggunakan, menyimpan, atau tidak melaporkan barang tersebut secara pribadi.', 2),
  ('housekeeping', '我本月有確實完成主管安排之公共區域清潔、整理及巡檢事項，未只完成房間而忽略公共空間。', 'Bulan ini saya menyelesaikan tugas pembersihan, penataan, dan pemeriksaan area umum yang diberikan oleh atasan. Saya tidak hanya membersihkan kamar dan mengabaikan area umum.', 3),
  ('housekeeping', '我本月有依排程完成每週、每月及每季保養項目，並於完成後留下必要紀錄或回報。', 'Bulan ini saya menyelesaikan tugas pemeliharaan mingguan, bulanan, dan triwulanan sesuai jadwal serta membuat catatan atau laporan yang diperlukan setelah tugas selesai.', 4),
  ('housekeeping', '我本月掃房時有依標準檢查床鋪、浴室、地面、檯面、備品、毛髮、污漬、異味及設備功能，未因趕房而省略必要步驟。', 'Saat memeriksa kamar pada bulan ini, saya mengikuti standar pemeriksaan untuk tempat tidur, kamar mandi, lantai, permukaan meja, perlengkapan tamu, rambut, noda, bau tidak sedap, serta fungsi peralatan. Saya tidak melewatkan langkah penting meskipun harus menyelesaikan kamar dengan cepat.', 5),
  ('housekeeping', '我本月完成房間清潔後，有再次自行檢查成果，確認房間達到可入住標準後才回報完成。', 'Setelah selesai membersihkan kamar pada bulan ini, saya selalu memeriksa kembali hasil pekerjaan dan hanya melaporkan pekerjaan selesai setelah memastikan kamar memenuhi standar untuk ditempati tamu.', 6),
  ('housekeeping', '我本月有依規定保管房卡、鑰匙、清潔工具及客房物品，未將房卡或客房資訊交由無關人員使用或知悉。', 'Bulan ini saya menyimpan dan menjaga kartu akses kamar, kunci, peralatan kebersihan, serta barang-barang kamar sesuai ketentuan. Saya tidak menyerahkan kartu akses atau informasi kamar kepada pihak yang tidak berkepentingan untuk digunakan atau diketahui.', 7),
  ('housekeeping', '我本月有正確使用清潔劑、機具及防護用品，並依規定補充、清潔、歸位及保管，避免造成安全風險或物品損壞。', 'Bulan ini saya menggunakan bahan pembersih, mesin, peralatan, dan perlengkapan pelindung dengan benar. Saya juga mengisi ulang, membersihkan, mengembalikan, dan menyimpannya sesuai ketentuan untuk mencegah risiko keselamatan atau kerusakan barang.', 8),
  ('housekeeping', '我本月有與客務部門保持良好房況溝通，針對急需房、延遲退房、維修房或特殊需求能即時確認及回報。', 'Bulan ini saya menjaga komunikasi yang baik dengan departemen Front Office mengenai status kamar. Untuk kamar yang dibutuhkan segera, keterlambatan check-out, kamar dalam perbaikan, atau permintaan khusus, saya segera melakukan konfirmasi dan memberikan laporan.', 9),
  ('housekeeping', '我本月有在要求時間內完成分配工作；如遇工作量過大、房況異常或無法如期完成，也有提早告知主管並尋求協助。', 'Bulan ini saya menyelesaikan pekerjaan yang diberikan dalam waktu yang ditentukan. Jika beban kerja terlalu banyak, terdapat kondisi kamar yang tidak normal, atau pekerjaan tidak dapat diselesaikan tepat waktu, saya telah memberi tahu atasan lebih awal dan meminta bantuan.', 10),
  ('frontdesk', '我本月在櫃檯遇到客人時，有起身主動問好，並邀請客人至櫃檯前就座辦理入住或相關事宜。', NULL, 1),
  ('frontdesk', '我本月面對客人問題時，始終維持良好態度；即使遇到客訴，也能以同理心協助處理，不將個人情緒帶入工作。', NULL, 2),
  ('frontdesk', '我本月每日交接事項都有再三確認，內容清楚完整，確保下一班同事能迅速掌握資訊並進入狀況。', NULL, 3),
  ('frontdesk', '我本月每日零用金、營收、洗衣機收入及其他款項都有確實點交；遇有異常時能即時回報並查明原因，未有隱瞞、私藏或延後處理之情形。', NULL, 4),
  ('frontdesk', '我本月於工作群組回報或向主管請示時，有使用自己的帳號，或至少清楚表明身分，確保資訊來源可辨識及可追蹤。', NULL, 5),
  ('frontdesk', '我本月每日櫃檯工作事項都有落實，並在規定或正確的時間內完成並誠實記錄。', NULL, 6),
  ('frontdesk', '我本月未於櫃檯飲食、長時間與同事聊天，或從事其他影響專業形象及客人觀感之行為。', NULL, 7),
  ('frontdesk', '我本月在巡房程序中維持一致標準，確實檢查掃房細節及異常事項，並依規定回報於工作群組。', NULL, 8),
  ('frontdesk', '我本月辦理入住、退房、付款或訂單異動前，有再次核對訂房姓名、房型、日期、款項及房況，避免因疏忽造成服務或帳務錯誤。', NULL, 9),
  ('frontdesk', '我本月有主動掌握當日入住名單、特殊需求、房況、活動及重要交辦事項，而非等到客人詢問或問題發生後才開始了解。', NULL, 10),
  ('frontdesk', '我本月有維持櫃檯、行李區及公共接待區域整潔，並主動留意客人可能需要協助之情形。', NULL, 11);
